num = input("Digite algo: ")
print("O tipo primitivo desse valor é", type(num))
print("Só tem espaços?", num.isspace())
print("É alfanumérico?", num.isalnum())
print("É alfabético?", num.isalpha())
print("É numérico?", num.isnumeric())
print("É decimal?", num.isdecimal())
print("É ASCII?", num.isascii())
print("Esta capitalizada?", num.istitle())
print(num.capitalize())
print(num.upper())
